version: '3.4'

services:
  seq:
    image: "datalust/seq:latest"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  mongonotificationsdata:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
     - sqlserver

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.API/Dockerfile
    depends_on:
      - sqlserver


  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Notification.API/Dockerfile
    depends_on:
      - mongonotificationsdata

  ocelot_identity_apigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: Ocelot_APIGw/Dockerfile

  ocelot_catalog_apigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: Ocelot_APIGw/Dockerfile

